import { useState } from 'react'
import {
    FileDown,
    Printer,
    Share2,
    MessageCircle,
    Check,
    Loader2
} from 'lucide-react'

interface ExportToolbarProps {
    topic: string
    content: string
    structured?: any
    grade?: number
}

export default function ExportToolbar({ topic, content, structured, grade }: ExportToolbarProps) {
    const [exporting, setExporting] = useState<string | null>(null)
    const [copied, setCopied] = useState(false)

    // Generate printable HTML content
    const generatePrintContent = () => {
        const structuredContent = structured ? Object.entries(structured)
            .filter(([key, val]) => val && key !== 'raw_response')
            .map(([key, val]) => {
                const title = key.replace(/_/g, ' ').replace(/\b\w/g, l => l.toUpperCase())
                let content = ''
                if (Array.isArray(val)) {
                    content = (val as string[]).map((item) => `<li>${typeof item === 'object' ? JSON.stringify(item) : item}</li>`).join('')
                    content = `<ul>${content}</ul>`
                } else if (typeof val === 'object') {
                    content = `<pre>${JSON.stringify(val, null, 2)}</pre>`
                } else {
                    content = `<p>${val}</p>`
                }
                return `<div class="section"><h3>${title}</h3>${content}</div>`
            }).join('') : `<p>${content}</p>`

        return `
<!DOCTYPE html>
<html>
<head>
    <title>${topic} - Teaching Guide</title>
    <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { font-family: 'Segoe UI', Arial, sans-serif; padding: 40px; max-width: 800px; margin: 0 auto; line-height: 1.6; }
        h1 { color: #1e40af; border-bottom: 3px solid #3b82f6; padding-bottom: 10px; margin-bottom: 20px; }
        h2 { color: #374151; margin-top: 10px; font-size: 14px; }
        h3 { color: #1e40af; margin-top: 20px; margin-bottom: 10px; font-size: 16px; border-left: 4px solid #3b82f6; padding-left: 10px; }
        .section { margin-bottom: 20px; padding: 15px; background: #f8fafc; border-radius: 8px; }
        ul { margin-left: 20px; }
        li { margin: 5px 0; }
        pre { background: #f1f5f9; padding: 10px; border-radius: 4px; font-size: 12px; overflow-x: auto; }
        .header-info { display: flex; gap: 20px; margin-bottom: 20px; color: #6b7280; font-size: 14px; }
        .footer { margin-top: 40px; padding-top: 20px; border-top: 1px solid #e5e7eb; color: #9ca3af; font-size: 12px; text-align: center; }
        @media print { body { padding: 20px; } .no-print { display: none; } }
    </style>
</head>
<body>
    <h1>📚 ${topic}</h1>
    <div class="header-info">
        ${grade ? `<span>🎓 Class ${grade}</span>` : ''}
        <span>📅 ${new Date().toLocaleDateString('en-IN')}</span>
    </div>
    ${structuredContent}
    <div class="footer">Generated by Pathshala Teaching Assistant</div>
</body>
</html>`
    }

    // Handle Print
    const handlePrint = () => {
        setExporting('print')
        const printWindow = window.open('', '_blank')
        if (!printWindow) {
            alert('Please allow popups to print')
            setExporting(null)
            return
        }
        printWindow.document.write(generatePrintContent())
        printWindow.document.close()
        setTimeout(() => {
            printWindow.print()
            setExporting(null)
        }, 500)
    }

    // Handle PDF Download (uses print to PDF)
    const handlePDF = () => {
        setExporting('pdf')
        const printWindow = window.open('', '_blank')
        if (!printWindow) {
            alert('Please allow popups to download PDF')
            setExporting(null)
            return
        }
        printWindow.document.write(generatePrintContent())
        printWindow.document.close()
        setTimeout(() => {
            printWindow.print()
            setExporting(null)
        }, 500)
    }

    // Handle WhatsApp Share
    const handleWhatsApp = () => {
        setExporting('whatsapp')

        // Create a simplified text version for WhatsApp
        let text = `📚 *${topic}*\n`
        if (grade) text += `🎓 Class ${grade}\n\n`

        if (structured) {
            if (structured.simple_explanation) {
                text += `💡 *Simple Explanation:*\n${structured.simple_explanation}\n\n`
            }
            if (structured.what_to_say) {
                text += `🗣️ *What to Say:*\n${structured.what_to_say}\n\n`
            }
            if (structured.check_for_understanding && Array.isArray(structured.check_for_understanding)) {
                text += `❓ *Quick Questions:*\n`
                structured.check_for_understanding.slice(0, 3).forEach((q: any, i: number) => {
                    text += `${i + 1}. ${typeof q === 'object' ? q.question : q}\n`
                })
            }
        } else {
            text += content.substring(0, 1000)
        }

        text += `\n\n_Generated by Pathshala_`

        // WhatsApp URL encode
        const whatsappUrl = `https://wa.me/?text=${encodeURIComponent(text)}`
        window.open(whatsappUrl, '_blank')
        setExporting(null)
    }

    // Copy to clipboard
    const handleCopy = async () => {
        let text = `${topic}\n\n`
        if (structured?.simple_explanation) {
            text += `Explanation: ${structured.simple_explanation}\n\n`
        }
        if (structured?.what_to_say) {
            text += `Teacher Script: ${structured.what_to_say}\n\n`
        }
        text += content

        await navigator.clipboard.writeText(text)
        setCopied(true)
        setTimeout(() => setCopied(false), 2000)
    }

    return (
        <div className="flex items-center gap-2">
            {/* Print Button */}
            <button
                onClick={handlePrint}
                disabled={exporting === 'print'}
                className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-gray-100 dark:bg-gray-700 text-gray-600 dark:text-gray-300 hover:bg-gray-200 dark:hover:bg-gray-600 transition-colors text-sm font-medium"
                title="Print as worksheet"
            >
                {exporting === 'print' ? <Loader2 className="w-4 h-4 animate-spin" /> : <Printer className="w-4 h-4" />}
                <span className="hidden sm:inline">Print</span>
            </button>

            {/* PDF Button */}
            <button
                onClick={handlePDF}
                disabled={exporting === 'pdf'}
                className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-red-100 dark:bg-red-900/30 text-red-600 dark:text-red-400 hover:bg-red-200 dark:hover:bg-red-900/50 transition-colors text-sm font-medium"
                title="Download as PDF"
            >
                {exporting === 'pdf' ? <Loader2 className="w-4 h-4 animate-spin" /> : <FileDown className="w-4 h-4" />}
                <span className="hidden sm:inline">PDF</span>
            </button>

            {/* WhatsApp Button */}
            <button
                onClick={handleWhatsApp}
                disabled={exporting === 'whatsapp'}
                className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-green-100 dark:bg-green-900/30 text-green-600 dark:text-green-400 hover:bg-green-200 dark:hover:bg-green-900/50 transition-colors text-sm font-medium"
                title="Share via WhatsApp"
            >
                {exporting === 'whatsapp' ? <Loader2 className="w-4 h-4 animate-spin" /> : <MessageCircle className="w-4 h-4" />}
                <span className="hidden sm:inline">WhatsApp</span>
            </button>

            {/* Copy Button */}
            <button
                onClick={handleCopy}
                className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-blue-100 dark:bg-blue-900/30 text-blue-600 dark:text-blue-400 hover:bg-blue-200 dark:hover:bg-blue-900/50 transition-colors text-sm font-medium"
                title="Copy to clipboard"
            >
                {copied ? <Check className="w-4 h-4" /> : <Share2 className="w-4 h-4" />}
                <span className="hidden sm:inline">{copied ? 'Copied!' : 'Copy'}</span>
            </button>
        </div>
    )
}
