"""add_analysis_fields_to_reflection

Revision ID: 2d7ab1367007
Revises: 9af7a328eac4
Create Date: 2026-01-14 21:06:58.413158

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d7ab1367007'
down_revision: Union[str, None] = '9af7a328eac4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reflections', sa.Column('pedagogical_sentiment', sa.String(length=50), nullable=True))
    op.add_column('reflections', sa.Column('analysis_json', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reflections', 'analysis_json')
    op.drop_column('reflections', 'pedagogical_sentiment')
    # ### end Alembic commands ###
