"""add_notifications_table

Revision ID: 348778f0a511
Revises: 24d4f373d4b6
Create Date: 2026-02-01 03:37:56.301687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '348778f0a511'
down_revision: Union[str, None] = '24d4f373d4b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_custom_roles_organization_id', table_name='custom_roles')
    op.drop_table('custom_roles')
    op.drop_index('ix_user_custom_roles_custom_role_id', table_name='user_custom_roles')
    op.drop_index('ix_user_custom_roles_user_id', table_name='user_custom_roles')
    op.drop_table('user_custom_roles')
    op.alter_column('teacher_content', 'is_vectorized',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('teacher_content', 'is_vectorized',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.create_table('user_custom_roles',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('custom_role_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['custom_role_id'], ['custom_roles.id'], name='user_custom_roles_custom_role_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_custom_roles_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='user_custom_roles_pkey')
    )
    op.create_index('ix_user_custom_roles_user_id', 'user_custom_roles', ['user_id'], unique=False)
    op.create_index('ix_user_custom_roles_custom_role_id', 'user_custom_roles', ['custom_role_id'], unique=False)
    op.create_table('custom_roles',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('base_role', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('permissions', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name='custom_roles_organization_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='custom_roles_pkey')
    )
    op.create_index('ix_custom_roles_organization_id', 'custom_roles', ['organization_id'], unique=False)
    # ### end Alembic commands ###
