"""add_observation_notes_to_crp_response

Revision ID: 8c45ac38ba99
Revises: 928f1c890120
Create Date: 2026-01-14 20:56:44.222207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8c45ac38ba99'
down_revision: Union[str, None] = '928f1c890120'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crp_responses', sa.Column('observation_notes', sa.Text(), nullable=True))
    op.add_column('queries', sa.Column('is_multigrade', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('queries', sa.Column('class_size', sa.Integer(), nullable=True))
    op.add_column('queries', sa.Column('instructional_time_minutes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('queries', 'instructional_time_minutes')
    op.drop_column('queries', 'class_size')
    op.drop_column('queries', 'is_multigrade')
    op.drop_column('crp_responses', 'observation_notes')
    # ### end Alembic commands ###
