"""add_is_best_practice

Revision ID: 928f1c890120
Revises: 
Create Date: 2026-01-13 17:27:59.961492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '928f1c890120'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_course_chats_course_id', table_name='course_chats')
    op.drop_index('ix_course_chats_student_id', table_name='course_chats')
    op.drop_table('course_chats')
    op.drop_index('ix_student_enrollments_course_id', table_name='student_enrollments')
    op.drop_index('ix_student_enrollments_student_id', table_name='student_enrollments')
    op.drop_table('student_enrollments')
    op.drop_index('ix_courses_created_by_id', table_name='courses')
    op.drop_index('ix_courses_grade', table_name='courses')
    op.drop_index('ix_courses_organization_id', table_name='courses')
    op.drop_index('ix_courses_subject', table_name='courses')
    op.drop_table('courses')
    op.add_column('crp_responses', sa.Column('is_best_practice', sa.Boolean(), nullable=False))
    op.add_column('organization_settings', sa.Column('litellm_api_key', sa.Text(), nullable=True))
    op.add_column('organization_settings', sa.Column('litellm_base_url', sa.String(length=500), nullable=True))
    op.add_column('organization_settings', sa.Column('litellm_model', sa.String(length=100), nullable=False))
    op.alter_column('users', 'is_verified',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_index(op.f('ix_users_organization_id'), 'users', ['organization_id'], unique=False)
    op.create_foreign_key(None, 'users', 'organizations', ['organization_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_organization_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.alter_column('users', 'is_verified',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_column('organization_settings', 'litellm_model')
    op.drop_column('organization_settings', 'litellm_base_url')
    op.drop_column('organization_settings', 'litellm_api_key')
    op.drop_column('crp_responses', 'is_best_practice')
    op.create_table('courses',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('courses_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_by_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('subject', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('grade', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('topic', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('enrollment_code', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('content', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('duration_minutes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('DRAFT', 'PUBLISHED', 'ARCHIVED', name='coursestatus'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('published_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name='courses_created_by_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name='courses_organization_id_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='courses_pkey'),
    sa.UniqueConstraint('enrollment_code', name='courses_enrollment_code_key'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_courses_subject', 'courses', ['subject'], unique=False)
    op.create_index('ix_courses_organization_id', 'courses', ['organization_id'], unique=False)
    op.create_index('ix_courses_grade', 'courses', ['grade'], unique=False)
    op.create_index('ix_courses_created_by_id', 'courses', ['created_by_id'], unique=False)
    op.create_table('student_enrollments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('course_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('progress', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('completion_percent', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('enrolled_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('last_accessed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name='student_enrollments_course_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name='student_enrollments_student_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='student_enrollments_pkey'),
    sa.UniqueConstraint('student_id', 'course_id', name='unique_student_course')
    )
    op.create_index('ix_student_enrollments_student_id', 'student_enrollments', ['student_id'], unique=False)
    op.create_index('ix_student_enrollments_course_id', 'student_enrollments', ['course_id'], unique=False)
    op.create_table('course_chats',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('course_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('response', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_on_topic', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('processing_time_ms', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name='course_chats_course_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name='course_chats_student_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='course_chats_pkey')
    )
    op.create_index('ix_course_chats_student_id', 'course_chats', ['student_id'], unique=False)
    op.create_index('ix_course_chats_course_id', 'course_chats', ['course_id'], unique=False)
    # ### end Alembic commands ###
