"""add_voice_note_transcript_to_crp_response

Revision ID: 9af7a328eac4
Revises: 8c45ac38ba99
Create Date: 2026-01-14 21:05:20.212639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9af7a328eac4'
down_revision: Union[str, None] = '8c45ac38ba99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_custom_roles_custom_role_id', table_name='user_custom_roles')
    op.drop_index('ix_user_custom_roles_user_id', table_name='user_custom_roles')
    op.drop_table('user_custom_roles')
    op.drop_index('ix_custom_roles_organization_id', table_name='custom_roles')
    op.drop_table('custom_roles')
    op.add_column('crp_responses', sa.Column('voice_note_transcript', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('crp_responses', 'voice_note_transcript')
    op.create_table('custom_roles',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('custom_roles_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('base_role', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('permissions', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name='custom_roles_organization_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='custom_roles_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_custom_roles_organization_id', 'custom_roles', ['organization_id'], unique=False)
    op.create_table('user_custom_roles',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('custom_role_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['custom_role_id'], ['custom_roles.id'], name='user_custom_roles_custom_role_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_custom_roles_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='user_custom_roles_pkey')
    )
    op.create_index('ix_user_custom_roles_user_id', 'user_custom_roles', ['user_id'], unique=False)
    op.create_index('ix_user_custom_roles_custom_role_id', 'user_custom_roles', ['custom_role_id'], unique=False)
    # ### end Alembic commands ###
